"""add_property_search_indexes

Revision ID: 2b90c15aa172
Revises: 9aef1f88b47f
Create Date: 2026-07-24 17:26:11.706247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b90c15aa172'
down_revision = '9aef1f88b47f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_latitude'), 'properties', ['latitude'], unique=False)
    op.create_index(op.f('ix_properties_longitude'), 'properties', ['longitude'], unique=False)
    op.create_index(op.f('ix_properties_postal_code'), 'properties', ['postal_code'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_postal_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_longitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_latitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    # ### end Alembic commands ###
