"""Add RefreshToken model

Revision ID: 2da9d18bd859
Revises: 004_add_detailed_room
Create Date: 2026-03-02 16:56:52.868224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da9d18bd859'
down_revision = '004_add_detailed_room'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_index('ix_used_reset_tokens_token_hash', table_name='used_reset_tokens')
    op.drop_table('used_reset_tokens')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.create_foreign_key(None, 'onboarding_responses', 'users', ['user_id'], ['id'])
    op.drop_column('properties', 'is_location_verified')
    op.drop_column('properties', 'accepted_tenant_types')
    op.drop_column('properties', 'location_verified_at')
    op.drop_column('properties', 'accepted_guarantees')
    op.alter_column('property_manager_access', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('property_media_sessions', 'location_verified')
    op.drop_column('property_media_sessions', 'location_verified_at')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'country')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'address_line1')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'address_line2')
    op.drop_column('users', 'city')
    op.drop_column('users', 'contact_preferences')
    op.drop_column('users', 'postal_code')
    op.alter_column('verification_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('contact_preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"email_notifications": true, "sms_notifications": false, "push_notifications": true, "email_frequency": "instant", "preferred_contact": "email"}\'::json'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(), server_default=sa.text("'France'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('property_media_sessions', sa.Column('location_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('property_media_sessions', sa.Column('location_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('property_manager_access', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('properties', sa.Column('accepted_guarantees', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('location_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('accepted_tenant_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('is_location_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'onboarding_responses', type_='foreignkey')
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_table('used_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='used_reset_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='used_reset_tokens_pkey')
    )
    op.create_index('ix_used_reset_tokens_token_hash', 'used_reset_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
