"""add_matching_fields

Revision ID: 41ea184ba52d
Revises: b2baa825acf7
Create Date: 2026-01-27 15:31:47.680446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41ea184ba52d'
down_revision = 'b2baa825acf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('accepted_tenant_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('accepted_guarantees', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'accepted_guarantees')
    op.drop_column('properties', 'accepted_tenant_types')
    # ### end Alembic commands ###
