"""add_location_verification_fields

Revision ID: 44ebd345175e
Revises: 41ea184ba52d
Create Date: 2026-01-27 16:03:03.799537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ebd345175e'
down_revision = '41ea184ba52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_location_verified', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('location_verified_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'location_verified_at')
    op.drop_column('properties', 'is_location_verified')
    # ### end Alembic commands ###
