"""Add notifications table

Revision ID: 6c1df4b5c544
Revises: 7f687bd4f0e9
Create Date: 2026-01-31 19:36:28.510554

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c1df4b5c544"
down_revision = "7f687bd4f0e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
