"""Add document extraction cache table

Revision ID: 7f687bd4f0e9
Revises: d827573aade4
Create Date: 2026-01-30 12:07:58.586545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f687bd4f0e9'
down_revision = 'd827573aade4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('extraction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_file_hash'), 'document_extractions', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extractions_file_hash'), table_name='document_extractions')
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
