"""Add bio and profile_picture_url to users

Revision ID: 8831b118955d
Revises: 2da9d18bd859
Create Date: 2026-03-05 01:19:49.415011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8831b118955d'
down_revision = '2da9d18bd859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
