"""Add first_name

Revision ID: 9aef1f88b47f
Revises: eb1021a3f305
Create Date: 2026-07-24 02:07:15.422711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aef1f88b47f'
down_revision = 'eb1021a3f305'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
