"""Add Dispute model

Revision ID: a3da0984d64a
Revises: cb5f4fb85427
Create Date: 2026-02-02 00:16:21.050243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3da0984d64a'
down_revision = 'cb5f4fb85427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=True),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('accused_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('DAMAGE', 'APPLIANCE_FAILURE', 'SHARED_LIABILITY', 'CLEANING', 'OTHER', name='dispute_category_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'EVIDENCE_NEEDED', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='dispute_status_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_claimed', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('TENANT_WINS', 'LANDLORD_WINS', 'SPLIT', 'NONE', name='dispute_verdict_enum'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('final_report_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accused_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_lease_id'), 'disputes', ['lease_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_lease_id'), table_name='disputes', if_exists=True)
    op.execute(\"DROP TABLE IF EXISTS disputes CASCADE\")
    # ### end Alembic commands ###
