"""Add missing tables

Revision ID: b2baa825acf7
Revises: 007_user_address_fields
Create Date: 2026-01-22 14:59:39.300654

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2baa825acf7"
down_revision = "007_user_address_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("document_type", sa.String(), nullable=False),
        sa.Column("verification_status", sa.String(), nullable=True),
        sa.Column(
            "verification_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column(
            "snapshot_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        "ix_conversations_landlord_id", table_name="conversations", if_exists=True
    )
    op.drop_index(
        "ix_conversations_last_message_at", table_name="conversations", if_exists=True
    )
    op.drop_index(
        "ix_conversations_property_id", table_name="conversations", if_exists=True
    )
    op.drop_index(
        "ix_conversations_tenant_id", table_name="conversations", if_exists=True
    )
    op.drop_column("leases", "created_at")
    op.drop_column("leases", "updated_at")
    op.drop_index("ix_messages_conversation_id", table_name="messages", if_exists=True)
    op.drop_index("ix_messages_created_at", table_name="messages", if_exists=True)
    op.alter_column(
        "onboarding_responses", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "onboarding_responses",
        "responses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index(
        "idx_onboarding_user_id", table_name="onboarding_responses", if_exists=True
    )
    op.create_unique_constraint(
        "onboarding_responses_user_id_key", "onboarding_responses", ["user_id"]
    )
    op.add_column(
        "properties", sa.Column("dpe_rating", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "properties", sa.Column("ges_rating", sa.String(length=1), nullable=True)
    )
    op.add_column("properties", sa.Column("dpe_value", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("ges_value", sa.Integer(), nullable=True))
    op.add_column(
        "properties", sa.Column("surface_type", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "properties", sa.Column("construction_year", sa.Integer(), nullable=True)
    )
    op.add_column(
        "properties",
        sa.Column(
            "utilities_included", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "properties", sa.Column("is_caf_eligible", sa.Boolean(), nullable=True)
    )
    op.drop_index("idx_properties_city", table_name="properties", if_exists=True)
    op.drop_index("idx_properties_landlord", table_name="properties", if_exists=True)
    op.drop_index("idx_properties_rent", table_name="properties", if_exists=True)
    op.drop_index("idx_properties_status", table_name="properties", if_exists=True)
    op.drop_index(
        "ix_pm_access_landlord_id", table_name="property_manager_access", if_exists=True
    )
    op.drop_index(
        "ix_pm_access_property_manager_id",
        table_name="property_manager_access",
        if_exists=True,
    )
    op.create_index(
        op.f("ix_property_manager_access_landlord_id"),
        "property_manager_access",
        ["landlord_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_manager_access_property_manager_id"),
        "property_manager_access",
        ["property_manager_id"],
        unique=False,
    )
    op.drop_index(
        "idx_property_media_property", table_name="property_media", if_exists=True
    )
    op.drop_index(
        "idx_property_media_session", table_name="property_media", if_exists=True
    )
    op.drop_constraint(
        "property_media_property_id_fkey", "property_media", type_="foreignkey"
    )
    op.create_foreign_key(
        "property_media_property_id_fkey",
        "property_media",
        "properties",
        ["property_id"],
        ["id"],
    )
    op.drop_index(
        "idx_media_sessions_code", table_name="property_media_sessions", if_exists=True
    )
    op.drop_index(
        "idx_media_sessions_property",
        table_name="property_media_sessions",
        if_exists=True,
    )
    op.drop_constraint(
        "property_media_sessions_property_id_fkey",
        "property_media_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "property_media_sessions_property_id_fkey",
        "property_media_sessions",
        "properties",
        ["property_id"],
        ["id"],
    )
    op.drop_index("ix_team_members_email", table_name="team_members", if_exists=True)
    op.drop_index(
        "ix_team_members_invite_token", table_name="team_members", if_exists=True
    )
    op.alter_column(
        "users",
        "identity_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "employment_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "preferences",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_index("ix_users_email", table_name="users", if_exists=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.alter_column(
        "verification_records",
        "verification_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_column("visit_slots", "created_at")
    op.drop_column("visit_slots", "updated_at")
    op.drop_index(
        "ix_webhook_deliveries_created_at",
        table_name="webhook_deliveries",
        if_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_webhook_deliveries_created_at",
        "webhook_deliveries",
        ["created_at"],
        unique=False,
    )
    op.add_column(
        "visit_slots",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "visit_slots",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "verification_records",
        "verification_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_users_email"), table_name="users", if_exists=True)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.alter_column(
        "users",
        "preferences",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "employment_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "identity_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        "ix_team_members_invite_token", "team_members", ["invite_token"], unique=False
    )
    op.create_index("ix_team_members_email", "team_members", ["email"], unique=False)
    op.drop_constraint(
        "property_media_sessions_property_id_fkey",
        "property_media_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "property_media_sessions_property_id_fkey",
        "property_media_sessions",
        "properties",
        ["property_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "idx_media_sessions_property",
        "property_media_sessions",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        "idx_media_sessions_code",
        "property_media_sessions",
        ["verification_code"],
        unique=False,
    )
    op.drop_constraint(
        "property_media_property_id_fkey", "property_media", type_="foreignkey"
    )
    op.create_foreign_key(
        "property_media_property_id_fkey",
        "property_media",
        "properties",
        ["property_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "idx_property_media_session", "property_media", ["session_id"], unique=False
    )
    op.create_index(
        "idx_property_media_property", "property_media", ["property_id"], unique=False
    )
    op.drop_index(
        op.f("ix_property_manager_access_property_manager_id"),
        table_name="property_manager_access",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_property_manager_access_landlord_id"),
        table_name="property_manager_access",
        if_exists=True,
    )
    op.create_index(
        "ix_pm_access_property_manager_id",
        "property_manager_access",
        ["property_manager_id"],
        unique=False,
    )
    op.create_index(
        "ix_pm_access_landlord_id",
        "property_manager_access",
        ["landlord_id"],
        unique=False,
    )
    op.create_index("idx_properties_status", "properties", ["status"], unique=False)
    op.create_index("idx_properties_rent", "properties", ["monthly_rent"], unique=False)
    op.create_index(
        "idx_properties_landlord", "properties", ["landlord_id"], unique=False
    )
    op.create_index("idx_properties_city", "properties", ["city"], unique=False)
    op.drop_column("properties", "is_caf_eligible")
    op.drop_column("properties", "utilities_included")
    op.drop_column("properties", "construction_year")
    op.drop_column("properties", "surface_type")
    op.drop_column("properties", "ges_value")
    op.drop_column("properties", "dpe_value")
    op.drop_column("properties", "ges_rating")
    op.drop_column("properties", "dpe_rating")
    op.drop_constraint(
        "onboarding_responses_user_id_key", "onboarding_responses", type_="unique"
    )
    op.create_index(
        "idx_onboarding_user_id", "onboarding_responses", ["user_id"], unique=False
    )
    op.alter_column(
        "onboarding_responses",
        "responses",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "onboarding_responses", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_index("ix_messages_created_at", "messages", ["created_at"], unique=False)
    op.create_index(
        "ix_messages_conversation_id", "messages", ["conversation_id"], unique=False
    )
    op.add_column(
        "leases",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "leases",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_conversations_tenant_id", "conversations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_conversations_property_id", "conversations", ["property_id"], unique=False
    )
    op.create_index(
        "ix_conversations_last_message_at",
        "conversations",
        ["last_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_landlord_id", "conversations", ["landlord_id"], unique=False
    )
    op.execute("DROP TABLE IF EXISTS applications CASCADE")
    op.execute("DROP TABLE IF EXISTS documents CASCADE")
    # ### end Alembic commands ###
