"""Add ownership verification

Revision ID: c1d2e3f4g5h6
Revises: f1380d161d84
Create Date: 2026-04-30 00:46:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = 'f1380d161d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('ownership_verified', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('ownership_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'ownership_data')
    op.drop_column('properties', 'ownership_verified')
    # ### end Alembic commands ###
