"""Add Inventory and InventoryItem models

Revision ID: cb5f4fb85427
Revises: 46555b96e1d9
Create Date: 2026-02-02 00:09:01.144013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb5f4fb85427'
down_revision = '46555b96e1d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MOVE_IN', 'MOVE_OUT', 'INTERIM', name='inventory_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_TENANT_SIGNATURE', 'PENDING_LANDLORD_SIGNATURE', 'COMPLETED', 'CONTESTED', name='inventory_status_enum'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('signature_tenant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_landlord', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_lease_id'), 'inventories', ['lease_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', 'MISSING', name='item_condition_enum'), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items', if_exists=True)
    op.execute("DROP TABLE IF EXISTS inventory_items CASCADE")
    op.drop_index(op.f('ix_inventories_lease_id'), table_name='inventories', if_exists=True)
    op.execute("DROP TABLE IF EXISTS inventories CASCADE")
    sa.Enum(name='inventory_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='inventory_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='item_condition_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
