"""Add missing fields to media sessions

Revision ID: d827573aade4
Revises: 010_notifications
Create Date: 2026-01-30 11:27:23.061290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd827573aade4'
down_revision = '010_notifications'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_read', table_name='notifications', if_exists=True, if_exists=True)
    op.drop_index('ix_notifications_user_id', table_name='notifications', if_exists=True, if_exists=True)
    op.drop_index('ix_notifications_user_read', table_name='notifications', if_exists=True, if_exists=True)
    op.drop_table('notifications')
    op.add_column('property_media_sessions', sa.Column('location_verified', sa.Boolean(), nullable=True))
    op.add_column('property_media_sessions', sa.Column('location_verified_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('used_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('used_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('property_media_sessions', 'location_verified_at')
    op.drop_column('property_media_sessions', 'location_verified')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    # ### end Alembic commands ###
