"""Add missing fields to media sessions

Revision ID: d827573aade4
Revises: 010_notifications
Create Date: 2026-01-30 11:27:23.061290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd827573aade4'
down_revision = '010_notifications'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('property_media_sessions', sa.Column('location_verified', sa.Boolean(), nullable=True))
    op.add_column('property_media_sessions', sa.Column('location_verified_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('used_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('used_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('property_media_sessions', 'location_verified_at')
    op.drop_column('property_media_sessions', 'location_verified')

    # ### end Alembic commands ###
