"""Add TrustDossier and DossierShareLink

Revision ID: eb1021a3f305
Revises: a9c1e2d3f4b5
Create Date: 2026-07-19 14:44:33.076638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.utils.encryption

# revision identifiers, used by Alembic.
revision = 'eb1021a3f305'
down_revision = 'a9c1e2d3f4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trustdossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('credential_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trustdossiers_credential_id'), 'trustdossiers', ['credential_id'], unique=False)
    op.create_index(op.f('ix_trustdossiers_user_id'), 'trustdossiers', ['user_id'], unique=False)
    op.create_table('dossier_share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['trustdossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_share_links_dossier_id'), 'dossier_share_links', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_dossier_share_links_target_user_id'), 'dossier_share_links', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_dossier_share_links_token'), 'dossier_share_links', ['token'], unique=True)
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.alter_column('properties', 'caf_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'ownership_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'kbis_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'carte_g_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'insurance_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'insurance_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('users', 'insurance_data',
               existing_type=sa.TEXT(),
               type_=app.utils.encryption.EncryptedJSON(),
               existing_nullable=True)
    op.alter_column('users', 'deposit_binding_data',
               existing_type=sa.TEXT(),
               type_=app.utils.encryption.EncryptedJSON(),
               existing_nullable=True)
    op.alter_column('users', 'refresh_token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'deposit_binding_data',
               existing_type=app.utils.encryption.EncryptedJSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'insurance_data',
               existing_type=app.utils.encryption.EncryptedJSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'insurance_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('users', 'insurance_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'carte_g_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'kbis_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'ownership_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'caf_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey')
    )
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'], unique=True)
    op.drop_index(op.f('ix_dossier_share_links_token'), table_name='dossier_share_links')
    op.drop_index(op.f('ix_dossier_share_links_target_user_id'), table_name='dossier_share_links')
    op.drop_index(op.f('ix_dossier_share_links_dossier_id'), table_name='dossier_share_links')
    op.drop_table('dossier_share_links')
    op.drop_index(op.f('ix_trustdossiers_user_id'), table_name='trustdossiers')
    op.drop_index(op.f('ix_trustdossiers_credential_id'), table_name='trustdossiers')
    op.drop_table('trustdossiers')
    # ### end Alembic commands ###
