import { test, expect } from '@playwright/test';

test.describe('Landlord Listing Wizard', () => {
    // Emulate prefers-reduced-motion so the wizard's step transitions are
    // instant — deterministic clicks, no waiting on framer animations.
    test.use({ reducedMotion: 'reduce' });

    test.beforeEach(async ({ page }) => {
        // Log console messages & page errors
        page.on('console', msg => console.log(`BROWSER [${msg.type()}]:`, msg.text()));
        page.on('pageerror', err => console.log('BROWSER ERROR:', err.message, err.stack));

        // Set language before any page script runs.
        await page.addInitScript(() => {
            localStorage.setItem('app-language', 'en');
        });

        // Mock authenticated landlord session.
        // Use regex patterns so requests to the real backend (:8000) are also
        // intercepted — glob patterns like **/auth/me can fail to match full
        // URLs with a port when the browser bypasses the Next.js proxy.
        const landlordUser = {
            id: 'dummy-landlord-id',
            email: 'landlord@roomivo.com',
            full_name: 'Test Landlord',
            role: 'landlord',
            email_verified: true,
            identity_verified: true,
            employment_verified: true,
            trust_score: 95,
            onboarding_completed: true,
            available_roles: ['landlord'],
        };

        // /auth/refresh — must be registered before /auth/me
        await page.route(/\/auth\/refresh/, async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ access_token: 'dummy-token-for-landlord', token_type: 'bearer' }),
            });
        });

        // /auth/me/segment-config — more specific; registered before /auth/me
        await page.route(/\/auth\/me\/segment-config/, async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    segment: 'landlord',
                    segment_name: 'Landlord',
                    segment_type: 'supply',
                    dashboard_path: '/dashboard',
                    common_features: [],
                    segment_features: [],
                    all_features: [],
                    quick_actions: [],
                    settings: {},
                    verification_status: {
                        id_verified: true,
                        email_verified: true,
                        employment_verified: true,
                        onboarding_completed: true,
                    },
                }),
            });
        });

        // /auth/me (exact match — not the segment-config sub-path)
        await page.route(/\/auth\/me(?!\/segment-config)/, async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify(landlordUser),
            });
        });
    });

    test('should step through all 8 steps of the property creation wizard and submit successfully', async ({ page }) => {
        // Intercept AI suggestion endpoint
        await page.route('**/properties/generate-description', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    description: 'This is a beautiful property generated by Roomivo AI in English.'
                })
            });
        });

        // Mock the Photon geocoder so the address autocomplete returns a
        // selectable suggestion (clicking it is what populates address_line1,
        // which Step 2 validation requires).
        await page.route(/photon\.komoot\.io/ , async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    features: [{
                        type: 'Feature',
                        geometry: { type: 'Point', coordinates: [2.3318, 48.8686] },
                        properties: {
                            street: 'Rue de la Paix', housenumber: '10',
                            postcode: '75002', city: 'Paris', country: 'France',
                        },
                    }],
                }),
            });
        });

        
        await page.route("**/api/address/autocomplete**", async (route) => {
            await route.fulfill({
                status: 200,
                contentType: "application/json",
                body: JSON.stringify([
                    {
                        address: "10 Rue de la Paix",
                        city: "Paris",
                        postal_code: "75002",
                        display: "10 Rue de la Paix, 75002 Paris",
                        lat: 48.8686,
                        lng: 2.3318
                    }
                ])
            });
        });

        // Intercept location enrichment (called on Step 2 → 3)
        await page.route('**/location/enrich', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    latitude: 48.8686,
                    longitude: 2.3318,
                    public_transport: [],
                    nearby_landmarks: []
                })
            });
        });

        // Intercept properties creation POST
        await page.route('**/properties', async (route) => {
            await route.fulfill({
                status: 201,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    title: 'Haussmann Luxury Suite',
                    city: 'Paris',
                    monthly_rent: 1200
                })
            });
        });

        // Intercept media session creation POST
        await page.route('**/properties/d3b07384-d113-4a6a-8b85-d2793a6bfa95/media-session', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'f55a1a92-c1f0-4f55-a1a9-2c1f0f55a1a9',
                    property_id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    verification_code: 'VERIFY-1234',
                    expires_at: new Date(Date.now() + 3600 * 1000).toISOString()
                })
            });
        });

        // Go to new property creation page
        await page.goto('/properties/new');
        const acceptCookies = page.locator('button:has-text("Accept All"), button:has-text("Essential Only")').first();
        if (await acceptCookies.isVisible({ timeout: 3000 }).catch(() => false)) {
            await acceptCookies.click();
        }

        // Verify Step 1. This is a heavy page (~1300-line component) behind
        // ProtectedRoute (async auth check); under parallel load its first render
        // can be slow, so wait generously for the title input before asserting.
        const titleInput = page.locator('input[placeholder*="Listing title"]');
        await expect(titleInput).toBeVisible({ timeout: 45000 });
        await expect(page.locator('h1')).toContainText(/Create a listing/i);
        await titleInput.fill('Haussmann Luxury Suite');

        const getNextBtn = () => page.locator('button:has-text("Next Protocol"), button:has-text("Suivant"), button:has-text("Next"), button:has-text("Continue")').first();
        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();

        // Step 2: Location
        const addressInput = page.locator('#address-autocomplete-input');
        await expect(addressInput).toBeVisible();
        await addressInput.fill('10 Rue de la Paix');
        await page.locator('#city-input').fill('Paris');
        await page.locator('#zip-input').fill('75002');
        await page.waitForTimeout(300);

        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();
        await expect(page.locator('text=Step 3 of 8')).toBeVisible({ timeout: 15000 });

        // Step 3: Details — select DPE rating B
        const dpeB = page.locator('#dpe-rating-B, button[aria-label^="DPE rating B"]').first();
        await expect(dpeB).toBeVisible({ timeout: 15000 });
        await dpeB.scrollIntoViewIfNeeded();
        await dpeB.click();
        await expect(dpeB).toHaveClass(/bg-zinc-900/, { timeout: 15000 });
        
        const dpeVal = page.locator('input[placeholder="e.g. 150"]');
        await dpeVal.fill('150');
        const gesVal = page.locator('input[placeholder="e.g. 35"]');
        await gesVal.fill('35');
        await gesVal.blur();
        await page.waitForTimeout(500);

        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();
        await expect(page.locator('text=Step 4 of 8')).toBeVisible({ timeout: 15000 });

        // Step 4: Layout & Capacity
        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();
        await expect(page.locator('text=Step 5 of 8')).toBeVisible({ timeout: 15000 });

        // Step 5: Pricing
        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();
        await expect(page.locator('text=Step 6 of 8')).toBeVisible({ timeout: 15000 });

        // Step 6: Amenities
        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();
        await expect(page.locator('text=Step 7 of 8')).toBeVisible({ timeout: 15000 });

        // Step 7: Description & AI Suggestion
        // Use waitForResponse to guarantee the generate-description round-trip
        // completes (and React state settles) before we click Next. Without this,
        // the interceptor's auth-refresh race can cause validateStep(7) to read
        // an empty descriptionEn and block the transition to step 8.
        const aiSuggestBtn = page.locator('button:has-text("AI"), button:has-text("Generate")').first();
        await expect(aiSuggestBtn).toBeVisible({ timeout: 15000 });
        const aiResponsePromise = page.waitForResponse('**/properties/generate-description', { timeout: 15000 });
        await aiSuggestBtn.click();
        await aiResponsePromise;

        const textarea = page.locator('textarea');
        await expect(textarea).toHaveValue('This is a beautiful property generated by Roomivo AI in English.', { timeout: 15000 });
        await expect(getNextBtn()).toBeEnabled({ timeout: 15000 });
        await getNextBtn().click();

        // Step 8: Review & publish
        await expect(page.locator('text=Review & publish')).toBeVisible({ timeout: 15000 });
        await expect(page.locator('text=Haussmann Luxury Suite')).toBeVisible({ timeout: 15000 });

        const commitBtn = page.locator('button:has-text("Create listing")');
        await expect(commitBtn).toBeDisabled();
        await page.locator('#declaration-checkbox').check({ force: true });
        await expect(commitBtn).toBeEnabled({ timeout: 15000 });
        await commitBtn.click();

        // Step 9: Success screen with QRCode display
        await expect(page.locator('text=Draft Created')).toBeVisible({ timeout: 15000 });
        await expect(page.locator('text=VERIFY-1234')).toBeVisible({ timeout: 15000 });
    });
});
