import { test, expect } from '@playwright/test';

test.describe('Landlord Listing Wizard', () => {
    // Emulate prefers-reduced-motion so the wizard's step transitions are
    // instant — deterministic clicks, no waiting on framer animations.
    test.use({ reducedMotion: 'reduce' });

    test.beforeEach(async ({ page }) => {
        // Log console messages & page errors
        page.on('console', msg => console.log(`BROWSER [${msg.type()}]:`, msg.text()));
        page.on('pageerror', err => console.log('BROWSER ERROR:', err.message, err.stack));

        // Seed auth state BEFORE any page script runs (survives every navigation),
        // so ProtectedRoute's checkAuth() always sees the token — avoids the
        // race where the secure-login gate renders instead of the wizard.
        await page.addInitScript(() => {
            localStorage.setItem('access_token', 'dummy-token-for-landlord');
            localStorage.setItem('app-language', 'en');
        });

        // Mock authenticated landlord session
        await page.route('**/auth/me', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'dummy-landlord-id',
                    email: 'landlord@roomivo.com',
                    full_name: 'Test Landlord',
                    role: 'landlord',
                    email_verified: true,
                    identity_verified: true,
                    employment_verified: true,
                    trust_score: 95,
                    onboarding_completed: true,
                    available_roles: ['landlord']
                }),
            });
        });

        // Mock refresh so an incidental 401 never clears the seeded token.
        await page.route('**/auth/refresh', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ access_token: 'dummy-token-for-landlord', token_type: 'bearer' }),
            });
        });
    });

    test('should step through all 8 steps of the property creation wizard and submit successfully', async ({ page }) => {
        // Intercept AI suggestion endpoint
        await page.route('**/properties/generate-description', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    description: 'This is a beautiful property generated by Roomivo AI in English.'
                })
            });
        });

        // Mock the Photon geocoder so the address autocomplete returns a
        // selectable suggestion (clicking it is what populates address_line1,
        // which Step 2 validation requires).
        await page.route('**/photon.komoot.io/api/**', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    features: [{
                        type: 'Feature',
                        geometry: { type: 'Point', coordinates: [2.3318, 48.8686] },
                        properties: {
                            street: 'Rue de la Paix', housenumber: '10',
                            postcode: '75002', city: 'Paris', country: 'France',
                        },
                    }],
                }),
            });
        });

        // Intercept location enrichment (called on Step 2 → 3)
        await page.route('**/location/enrich', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    latitude: 48.8686,
                    longitude: 2.3318,
                    public_transport: [],
                    nearby_landmarks: []
                })
            });
        });

        // Intercept properties creation POST
        await page.route('**/properties', async (route) => {
            await route.fulfill({
                status: 201,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    title: 'Haussmann Luxury Suite',
                    city: 'Paris',
                    monthly_rent: 1200
                })
            });
        });

        // Intercept media session creation POST
        await page.route('**/properties/d3b07384-d113-4a6a-8b85-d2793a6bfa95/media-session', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'f55a1a92-c1f0-4f55-a1a9-2c1f0f55a1a9',
                    property_id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    verification_code: 'VERIFY-1234',
                    expires_at: new Date(Date.now() + 3600 * 1000).toISOString()
                })
            });
        });

        // Go to new property creation page
        await page.goto('/properties/new');

        // Verify Step 1. This is a heavy page (~1300-line component) behind
        // ProtectedRoute (async auth check); under parallel load its first render
        // can be slow, so wait generously for the title input before asserting.
        const titleInput = page.locator('input[placeholder*="Listing title"]');
        await expect(titleInput).toBeVisible({ timeout: 45000 });
        await expect(page.locator('h1')).toContainText(/Create a listing/i);
        await titleInput.fill('Haussmann Luxury Suite');

        const continueBtn = page.locator('button:has-text("Continue")');
        await continueBtn.click();

        // Step 2: Location — type in the autocomplete, then click the mocked
        // suggestion so address_line1/city/postal_code get populated (Step 2
        // validation requires all three).
        const addressInput = page.locator('input[placeholder*="typing an address"]');
        await expect(addressInput).toBeVisible();
        await addressInput.fill('10 Rue de la Paix');
        const suggestion = page.locator('li:has-text("Rue de la Paix")').first();
        await expect(suggestion).toBeVisible();
        await suggestion.click();
        await continueBtn.click();

        // Step 3: Details — select DPE rating B (exact aria-label avoids matching
        // other buttons that contain the letter "B").
        await page.getByRole('button', { name: 'DPE rating B', exact: true }).click();
        await continueBtn.click();

        // Step 4: Layout & Capacity
        await continueBtn.click();

        // Step 5: Pricing
        await continueBtn.click();

        // Step 6: Amenities
        await continueBtn.click();

        // Step 7: Description & AI Suggestion
        await expect(page.locator('text=07 // Description')).toBeVisible();
        const aiSuggestBtn = page.locator('button:has-text("AI Suggest")');
        await expect(aiSuggestBtn).toBeVisible();
        await aiSuggestBtn.click();

        // Check description was filled
        const textarea = page.locator('textarea');
        await expect(textarea).toHaveValue('This is a beautiful property generated by Roomivo AI in English.');
        await continueBtn.click();

        // Step 8: Review & publish
        await expect(page.locator('text=Review & publish')).toBeVisible();
        await expect(page.locator('text=Haussmann Luxury Suite')).toBeVisible();

        // The legal-declaration checkbox must be accepted before submit is enabled.
        const commitBtn = page.locator('button:has-text("Create listing")');
        await expect(commitBtn).toBeDisabled();
        // The checkbox is visually-hidden (sr-only) behind a styled control, so
        // force the check; assert it took effect via the enabled submit button.
        await page.locator('#declaration-checkbox').check({ force: true });
        await expect(commitBtn).toBeEnabled();
        await commitBtn.click();

        // Step 9: Success screen with QRCode display
        await expect(page.locator('text=Draft Created')).toBeVisible({ timeout: 15000 });
        await expect(page.locator('text=VERIFY-1234')).toBeVisible();
    });
});
