import { test, expect } from '@playwright/test';

test.describe('Landlord Listing Wizard', () => {
    
    test.beforeEach(async ({ page }) => {
        // Log console messages & page errors
        page.on('console', msg => console.log(`BROWSER [${msg.type()}]:`, msg.text()));
        page.on('pageerror', err => console.log('BROWSER ERROR:', err.message, err.stack));

        // Mock authenticated landlord session
        await page.route('**/auth/me', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'dummy-landlord-id',
                    email: 'landlord@roomivo.com',
                    full_name: 'Test Landlord',
                    role: 'landlord',
                    email_verified: true,
                    identity_verified: true,
                    employment_verified: true,
                    trust_score: 95,
                    onboarding_completed: true,
                    available_roles: ['landlord']
                }),
            });
        });

        // Set access token so checkAuth knows we are logged in
        await page.goto('/');
        await page.evaluate(() => {
            localStorage.setItem('access_token', 'dummy-token-for-landlord');
            localStorage.setItem('app-language', 'en');
        });
        await page.reload();
    });

    test('should step through all 8 steps of the property creation wizard and submit successfully', async ({ page }) => {
        // Intercept AI suggestion endpoint
        await page.route('**/properties/generate-description', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    description: 'This is a beautiful property generated by Roomivo AI in English.'
                })
            });
        });

        // Intercept properties creation POST
        await page.route('**/properties', async (route) => {
            await route.fulfill({
                status: 201,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    title: 'Haussmann Luxury Suite',
                    city: 'Paris',
                    monthly_rent: 1200
                })
            });
        });

        // Intercept media session creation POST
        await page.route('**/properties/d3b07384-d113-4a6a-8b85-d2793a6bfa95/media-session', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    id: 'f55a1a92-c1f0-4f55-a1a9-2c1f0f55a1a9',
                    property_id: 'd3b07384-d113-4a6a-8b85-d2793a6bfa95',
                    verification_code: 'VERIFY-1234',
                    expires_at: new Date(Date.now() + 3600 * 1000).toISOString()
                })
            });
        });

        // Go to new property creation page
        await page.goto('/properties/new');

        // Verify Step 1
        await expect(page.locator('h1')).toContainText(/Listing Protocol/i);
        const titleInput = page.locator('input[placeholder*="Lister Title"]');
        await expect(titleInput).toBeVisible();
        await titleInput.fill('Haussmann Luxury Suite');

        const continueBtn = page.locator('button:has-text("Continue")');
        await continueBtn.click();

        // Step 2: Geolocation
        const addressInput = page.locator('input[placeholder*="Search for address"]');
        await expect(addressInput).toBeVisible();
        await addressInput.fill('10 Rue de la Paix');
        const cityInput = page.locator('input:near(label:has-text("City"))').first();
        if (await cityInput.isVisible()) {
            await cityInput.fill('Paris');
        } else {
            await page.locator('input').nth(1).fill('Paris');
        }
        const zipInput = page.locator('input:near(label:has-text("Zip"))').first();
        if (await zipInput.isVisible()) {
            await zipInput.fill('75002');
        } else {
            await page.locator('input').nth(2).fill('75002');
        }
        await continueBtn.click();

        // Step 3: Details (Specs)
        // Click DPE Rating B
        const dpeB = page.locator('button:has-text("B")');
        await dpeB.click();
        await continueBtn.click();

        // Step 4: Layout & Capacity
        await continueBtn.click();

        // Step 5: Pricing
        await continueBtn.click();

        // Step 6: Amenities
        await continueBtn.click();

        // Step 7: Narrative & AI Suggestion
        await expect(page.locator('text=07 // Narrative')).toBeVisible();
        const aiSuggestBtn = page.locator('button:has-text("AI Suggest")');
        await expect(aiSuggestBtn).toBeVisible();
        await aiSuggestBtn.click();

        // Check description was filled
        const textarea = page.locator('textarea');
        await expect(textarea).toHaveValue('This is a beautiful property generated by Roomivo AI in English.');
        await continueBtn.click();

        // Step 8: Review & Commit
        await expect(page.locator('text=Review Protocol')).toBeVisible();
        await expect(page.locator('text=Haussmann Luxury Suite')).toBeVisible();

        const commitBtn = page.locator('button:has-text("Commit to Registry")');
        await expect(commitBtn).toBeVisible();
        await commitBtn.click();

        // Step 9: Success screen with QRCode display
        await expect(page.locator('text=Draft Created')).toBeVisible({ timeout: 15000 });
        await expect(page.locator('text=VERIFY-1234')).toBeVisible();
    });
});
